title: Искусство землепользования
description: землепользование, межевание, полный и точный кадастр недвижимости
subtitle: База знаний Национального союза землепользователей
location: Москва
date: true
count_post: 6

logo: /assets/img/logo.png

baseurl: ""
permalink: /:categories/:year/:month/:day/:title/

author:
  name      : С. И. Ивасюк
  email     : cgles@yandex.ru

social:
  - username: https://t.me/serge_si
  - links: https://t.me/land_use_art

organization:
  name      : Национальный союз землепользователей
  email     : info@nsz.su  

collections:
  info:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post   

# Build settings
exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  
markdown: kramdown
urlimg: '/assets/img/'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - assets/img