title: Искусство землепользования
description: землепользование, межевание, полный и точный кадастр недвижимости
subtitle: Проект "Национального союза землепользователей"
location: Москва
date: true
olddate: 180
count_post: 4

logo: /assets/img/logo.png

baseurl: ""
permalink: /:categories/:year/:month/:day/:title/

author:
  name      : С. И. Ивасюк
  email     : cgles@yandex.ru
  telegram_username  : https://t.me/serge_si

organization:
  name      : Национальный союз землепользователей
  email     : info@nsz.su  

collections:
  info:
    output: true
    sort_by: order
  articles:
    output: true
    sort_by: date
  materials: 
    output: true
  results:  
    output: true

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: post   
      supertitle: К списку статей
      superpermalink: /articles/ 
  - scope:
      path: ""
      type: posts
    values:
      layout: post   
  - scope:
      path: ""
      type: pages
    values:
      layout: doc
      supertitle: К материалам проекта
      superpermalink: /materials/ 
  - scope:
      path: ""
      type: materials
    values:
      layout: doc
      supertitle: К материалам проекта
      superpermalink: /materials/ 
  - scope:
      path: ""
      type: results
    values:
      layout: doc
      supertitle: К материалам проекта
      superpermalink: /materials/               

# Build settings
exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  
markdown: kramdown
urlimg: '/assets/img/'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Social media
telegram: telegram